[phases.setup]
packages = [ "python" ]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r TGBot/requirements.txt"
]

[phases.build]
# ничего не нужно собирать для Python-приложения

[phases.start]
cmd = "python TGBot/main_webhook.py"
